import { NextResponse } from 'next/server'
import { z } from 'zod'
import type { assertAdmin } from './cms-auth'
import { invalidateProductListReferenceData } from './product-list-reference-cache'
import { buildCombinedMetalDisplayLabel } from './product-metal-variants'

type Access=Exclude<Awaited<ReturnType<typeof assertAdmin>>,{error:NextResponse}>
type RpcError={code?:string;message?:string}
type RpcClient={rpc:(name:string,args:Record<string,unknown>)=>PromiseLike<{data:unknown;error:RpcError|null}>}
const optional=(max=2_000)=>z.string().max(max).nullable().optional()
const metal=z.object({name:z.string().trim().min(1).max(200),slug:z.string().trim().min(1).max(200).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),purity_label:optional(100),base_metal_name:optional(200),display_label:optional(300),is_combined_option:z.boolean(),color_hex:optional(50),composition_description:optional(5_000),display_order:z.coerce.number().int().min(0).max(1_000_000),status:z.enum(['active','hidden'])}).strict()
const part=z.object({id:z.coerce.number().int().positive().optional(),part_name:z.string().trim().min(1).max(200),percentage:z.coerce.number().min(0).max(100),color_hex:optional(50),sort_order:z.coerce.number().int().min(0).max(1_000_000)}).strict()
const saveEnvelope=z.object({request_id:z.string().uuid(),expected_revision:z.string().regex(/^[a-f0-9]{32}$/).nullable(),metal:z.record(z.string(),z.unknown()),parts:z.array(z.record(z.string(),z.unknown())).max(500),deleted_part_ids:z.array(z.coerce.number().int().positive()).max(500)}).strict()
const deleteEnvelope=z.object({request_id:z.string().uuid(),expected_revision:z.string().regex(/^[a-f0-9]{32}$/)}).strict()
export type CatalogMetalRow=Record<string,unknown>&{id:string;_revision:string;composition_parts:Array<Record<string,unknown>&{id:number}>}
type Snapshot={item:CatalogMetalRow|null;revision:string}

export async function loadCatalogMetalList(client:RpcClient){const{data,error}=await client.rpc('catalog_metal_list_v1',{});if(error)throw new Error(error.code==='PGRST202'||error.code==='42883'?'Metals are awaiting their database migration.':'Unable to load metals.');return(Array.isArray(data)?data:[])as CatalogMetalRow[]}
export async function loadCatalogMetal(client:RpcClient,id:string){const{data,error}=await client.rpc('catalog_metal_row_v1',{p_id:id});if(error)throw new Error(error.code==='PGRST202'||error.code==='42883'?'Metals are awaiting their database migration.':'Unable to load this metal.');return(data as Snapshot).item}
function errorResponse(error:RpcError,action:'save'|'delete'){if(error.code==='PGRST202'||error.code==='42883')return NextResponse.json({error:'Metals are awaiting their database update. Existing data was not changed.'},{status:503});if(error.code==='40001'||error.code==='P0001')return NextResponse.json({error:error.message},{status:409});if(error.code==='P0002')return NextResponse.json({error:'This metal no longer exists.'},{status:404});if(error.code==='42501')return NextResponse.json({error:error.message},{status:403});if(['22023','22P02','23502','23503','23505','23514'].includes(error.code??''))return NextResponse.json({error:error.message},{status:400});return NextResponse.json({error:`Unable to ${action} this metal. No partial changes were committed.`},{status:500})}
export async function listCatalogMetals(access:Access){try{return NextResponse.json({items:await loadCatalogMetalList(access.adminClient)},{headers:{'Cache-Control':'no-store'}})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Unable to load metals.'},{status:503})}}
export async function saveCatalogMetal(access:Access,id:string|null,input:unknown){const envelope=saveEnvelope.safeParse(input);if(!envelope.success)return NextResponse.json({error:envelope.error.issues[0]?.message??'Invalid metal save request.'},{status:400});if((id===null)!==(envelope.data.expected_revision===null))return NextResponse.json({error:id===null?'New metals cannot include an existing revision.':'An existing revision is required.'},{status:400});const parsedId=id===null?null:z.string().uuid().safeParse(id);if(parsedId!==null&&!parsedId.success)return NextResponse.json({error:'Invalid metal ID.'},{status:400});const parsedMetal=metal.safeParse(envelope.data.metal),parsedParts=z.array(part).safeParse(envelope.data.parts);if(!parsedMetal.success)return NextResponse.json({error:parsedMetal.error.issues[0]?.message??'Invalid metal details.'},{status:400});if(!parsedParts.success)return NextResponse.json({error:parsedParts.error.issues[0]?.message??'Invalid composition details.'},{status:400});if(new Set(parsedParts.data.flatMap(x=>x.id?[x.id]:[])).size!==parsedParts.data.filter(x=>x.id).length||new Set(envelope.data.deleted_part_ids).size!==envelope.data.deleted_part_ids.length)return NextResponse.json({error:'Composition IDs must be unique.'},{status:400});const base=parsedMetal.data.base_metal_name?.trim()||parsedMetal.data.name;const label=buildCombinedMetalDisplayLabel({...parsedMetal.data,base_metal_name:base});const normalized={...parsedMetal.data,name:parsedMetal.data.is_combined_option?label:parsedMetal.data.name,base_metal_name:base,display_label:label};const{data,error}=await access.adminClient.rpc('catalog_metal_save_v1',{p_actor_id:access.user.id,p_request_id:envelope.data.request_id,p_expected_revision:envelope.data.expected_revision,p_id:parsedId===null?null:parsedId.data,p_metal:normalized,p_parts:parsedParts.data,p_deleted_part_ids:envelope.data.deleted_part_ids});if(error)return errorResponse(error,'save');invalidateProductListReferenceData();return NextResponse.json(data,{headers:{'Cache-Control':'no-store'}})}
export async function deleteCatalogMetal(access:Access,id:string,input:unknown){const parsedId=z.string().uuid().safeParse(id),envelope=deleteEnvelope.safeParse(input);if(!parsedId.success||!envelope.success)return NextResponse.json({error:'A valid metal ID, request ID, and revision are required.'},{status:400});const{data,error}=await access.adminClient.rpc('catalog_metal_delete_v1',{p_actor_id:access.user.id,p_request_id:envelope.data.request_id,p_expected_revision:envelope.data.expected_revision,p_id:parsedId.data});if(error)return errorResponse(error,'delete');invalidateProductListReferenceData();return NextResponse.json(data,{headers:{'Cache-Control':'no-store'}})}
