begin;

create or replace function public.catalog_hierarchy_list_v1(p_kind text)
returns jsonb language plpgsql security definer set search_path=public stable as $$
declare v_items jsonb;
begin
  case p_kind
    when 'category' then select coalesce(jsonb_agg((to_jsonb(x)-'created_at'-'updated_at')||jsonb_build_object('_revision',md5((to_jsonb(x)-'created_at'-'updated_at')::text)) order by x.display_order,x.name,x.id),'[]') into v_items from public.catalog_categories x;
    when 'subcategory' then select coalesce(jsonb_agg((to_jsonb(x)-'created_at'-'updated_at')||jsonb_build_object('_revision',md5((to_jsonb(x)-'created_at'-'updated_at')::text)) order by x.category_id,x.display_order,x.name,x.id),'[]') into v_items from public.catalog_subcategories x;
    when 'option' then select coalesce(jsonb_agg((to_jsonb(x)-'created_at'-'updated_at')||jsonb_build_object('_revision',md5((to_jsonb(x)-'created_at'-'updated_at')::text)) order by x.subcategory_id,x.display_order,x.name,x.id),'[]') into v_items from public.catalog_options x;
    else raise exception 'Unsupported catalog hierarchy type.' using errcode='22023';
  end case; return v_items;
end $$;

create or replace function public.catalog_hierarchy_row_v1(p_kind text,p_id uuid)
returns jsonb language plpgsql security definer set search_path=public stable as $$
declare v_item jsonb;v_revision text;
begin
  case p_kind
    when 'category' then select to_jsonb(x) into v_item from public.catalog_categories x where x.id=p_id;
    when 'subcategory' then select to_jsonb(x) into v_item from public.catalog_subcategories x where x.id=p_id;
    when 'option' then select to_jsonb(x) into v_item from public.catalog_options x where x.id=p_id;
    else raise exception 'Unsupported catalog hierarchy type.' using errcode='22023';
  end case;
  v_revision:=md5(coalesce((v_item-'created_at'-'updated_at')::text,'null'));
  return jsonb_build_object('item',case when v_item is null then null else (v_item-'created_at'-'updated_at')||jsonb_build_object('_revision',v_revision) end,'revision',v_revision);
end $$;

create or replace function public.catalog_hierarchy_save_v1(p_actor_id uuid,p_request_id uuid,p_expected_revision text,p_kind text,p_id uuid,p_item jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_before jsonb;v_result jsonb;v_receipt public.cms_save_receipts%rowtype;v_hash text:=md5(jsonb_build_object('kind',p_kind,'id',p_id,'revision',p_expected_revision,'item',p_item)::text);v_id uuid;v_name text:=trim(coalesce(p_item->>'name',''));v_slug text:=lower(regexp_replace(regexp_replace(trim(coalesce(p_item->>'slug','')),'[^a-zA-Z0-9]+','-','g'),'(^-|-$)','','g'));v_status text:=coalesce(p_item->>'status','active');v_order int;v_parent uuid;v_locked boolean;v_old_parent uuid;v_nav text;v_show boolean;v_direct text;
begin
  if not exists(select 1 from public.profiles p where p.id=p_actor_id and p.role='admin') then raise exception 'Administrator access is required.' using errcode='42501';end if;
  if p_request_id is null or p_item is null or jsonb_typeof(p_item)<>'object' then raise exception 'Invalid hierarchy save request.' using errcode='22023';end if;
  perform pg_advisory_xact_lock(hashtextextended('catalog-request:'||p_actor_id||':'||p_request_id,0));select * into v_receipt from public.cms_save_receipts r where r.actor_id=p_actor_id and r.request_id=p_request_id;
  if found then if v_receipt.operation<>'catalog-hierarchy-save-'||p_kind or v_receipt.payload_hash<>v_hash then raise exception 'This request ID was already used for a different save.' using errcode='22023';end if;return v_receipt.result;end if;
  perform pg_advisory_xact_lock(hashtextextended('catalog-hierarchy:'||p_kind||':'||coalesce(p_id::text,'new'),0));
  if p_id is null then if p_expected_revision is not null then raise exception 'New records cannot include an existing revision.' using errcode='22023';end if;else v_before:=public.catalog_hierarchy_row_v1(p_kind,p_id);if v_before->'item'='null'::jsonb then raise exception 'Hierarchy record not found.' using errcode='P0002';end if;if p_expected_revision is null or v_before->>'revision'<>p_expected_revision then raise exception 'This hierarchy record changed since you opened it. Reload before saving.' using errcode='40001';end if;end if;
  begin v_order:=coalesce((p_item->>'display_order')::int,0);exception when others then raise exception 'Display order must be a whole number.' using errcode='22023';end;
  if v_name='' or v_slug='' or v_status not in('active','hidden') or v_order<0 or v_order>1000000 then raise exception 'Invalid hierarchy name, slug, status, or display order.' using errcode='22023';end if;
  case p_kind
    when 'category' then
      if exists(select 1 from jsonb_object_keys(p_item) k where k<>all(array['code','name','slug','show_in_nav','nav_type','direct_link_url','display_order','status','banner_desktop_image_path','banner_mobile_image_path','banner_desktop_image_alt','banner_mobile_image_alt','banner_title','banner_subtitle','banner_cta_label','banner_cta_link','banner_enabled'])) then raise exception 'Category payload contains unsupported fields.' using errcode='22023';end if;
      if trim(coalesce(p_item->>'code',''))='' then raise exception 'Category code is required.' using errcode='22023';end if;
      if exists(select 1 from public.catalog_categories x where (lower(x.name)=lower(v_name) or x.slug=v_slug or upper(x.code)=upper(trim(p_item->>'code'))) and (p_id is null or x.id<>p_id)) then raise exception 'A category with this name, slug, or code already exists.' using errcode='23505';end if;
      v_show:=coalesce((p_item->>'show_in_nav')::boolean,true);v_nav:=case when not v_show then null else nullif(p_item->>'nav_type','') end;
      if v_nav not in('mega_menu','direct_link') and v_show then raise exception 'Choose Mega Menu or Direct Link navigation.' using errcode='22023';end if;
      v_direct:=case when not v_show or v_nav='mega_menu' then null else coalesce(nullif(trim(p_item->>'direct_link_url'),''),'/'||v_slug) end;
      if p_id is null then insert into public.catalog_categories(code,name,slug,show_in_nav,nav_type,direct_link_url,display_order,status,banner_desktop_image_path,banner_mobile_image_path,banner_desktop_image_alt,banner_mobile_image_alt,banner_title,banner_subtitle,banner_cta_label,banner_cta_link,banner_enabled) values(upper(trim(p_item->>'code')),v_name,v_slug,v_show,v_nav::public.catalog_nav_type,v_direct,v_order,v_status::public.catalog_status,nullif(trim(p_item->>'banner_desktop_image_path'),''),nullif(trim(p_item->>'banner_mobile_image_path'),''),nullif(trim(p_item->>'banner_desktop_image_alt'),''),nullif(trim(p_item->>'banner_mobile_image_alt'),''),nullif(trim(p_item->>'banner_title'),''),nullif(trim(p_item->>'banner_subtitle'),''),nullif(trim(p_item->>'banner_cta_label'),''),nullif(trim(p_item->>'banner_cta_link'),''),coalesce((p_item->>'banner_enabled')::boolean,false)) returning id into v_id;
      else
        select is_system_locked into v_locked from public.catalog_categories where id=p_id;
        if v_locked and ((v_before->'item'->>'code',v_before->'item'->>'name',v_before->'item'->>'slug',(v_before->'item'->>'show_in_nav')::boolean,v_before->'item'->>'nav_type',v_before->'item'->>'direct_link_url',(v_before->'item'->>'display_order')::int,v_before->'item'->>'status') is distinct from (upper(trim(p_item->>'code')),v_name,v_slug,v_show,v_nav,v_direct,v_order,v_status)) then raise exception 'This protected system category only allows banner changes.' using errcode='42501';end if;
        update public.catalog_categories x set code=case when v_locked then x.code else upper(trim(p_item->>'code')) end,name=case when v_locked then x.name else v_name end,slug=case when v_locked then x.slug else v_slug end,show_in_nav=case when v_locked then x.show_in_nav else v_show end,nav_type=case when v_locked then x.nav_type else v_nav::public.catalog_nav_type end,direct_link_url=case when v_locked then x.direct_link_url else v_direct end,display_order=case when v_locked then x.display_order else v_order end,status=case when v_locked then x.status else v_status::public.catalog_status end,banner_desktop_image_path=case when p_item?'banner_desktop_image_path' then nullif(trim(p_item->>'banner_desktop_image_path'),'') else x.banner_desktop_image_path end,banner_mobile_image_path=case when p_item?'banner_mobile_image_path' then nullif(trim(p_item->>'banner_mobile_image_path'),'') else x.banner_mobile_image_path end,banner_desktop_image_alt=case when p_item?'banner_desktop_image_alt' then nullif(trim(p_item->>'banner_desktop_image_alt'),'') else x.banner_desktop_image_alt end,banner_mobile_image_alt=case when p_item?'banner_mobile_image_alt' then nullif(trim(p_item->>'banner_mobile_image_alt'),'') else x.banner_mobile_image_alt end,banner_title=case when p_item?'banner_title' then nullif(trim(p_item->>'banner_title'),'') else x.banner_title end,banner_subtitle=case when p_item?'banner_subtitle' then nullif(trim(p_item->>'banner_subtitle'),'') else x.banner_subtitle end,banner_cta_label=case when p_item?'banner_cta_label' then nullif(trim(p_item->>'banner_cta_label'),'') else x.banner_cta_label end,banner_cta_link=case when p_item?'banner_cta_link' then nullif(trim(p_item->>'banner_cta_link'),'') else x.banner_cta_link end,banner_enabled=case when p_item?'banner_enabled' then (p_item->>'banner_enabled')::boolean else x.banner_enabled end,updated_at=now() where x.id=p_id;v_id:=p_id;
      end if;
    when 'subcategory' then
      if exists(select 1 from jsonb_object_keys(p_item) k where k<>all(array['category_id','name','slug','sub_type','icon_svg_path','image_path','image_alt','display_order','status'])) then raise exception 'Subcategory payload contains unsupported fields.' using errcode='22023';end if;
      v_parent:=nullif(p_item->>'category_id','')::uuid;if not exists(select 1 from public.catalog_categories x where x.id=v_parent) then raise exception 'Parent category does not exist.' using errcode='23503';end if;
      if coalesce(p_item->>'sub_type','standard') not in('standard','auto_shape','manual_style','auto_metal','gender_split') then raise exception 'Invalid subcategory type.' using errcode='22023';end if;
      if exists(select 1 from public.catalog_subcategories x where x.category_id=v_parent and (lower(x.name)=lower(v_name) or x.slug=v_slug) and (p_id is null or x.id<>p_id)) then raise exception 'A subcategory with this name or slug already exists in the category.' using errcode='23505';end if;
      if p_id is null then insert into public.catalog_subcategories(category_id,name,slug,sub_type,icon_svg_path,image_path,image_alt,display_order,status) values(v_parent,v_name,v_slug,coalesce(p_item->>'sub_type','standard')::public.catalog_sub_type,nullif(trim(p_item->>'icon_svg_path'),''),coalesce(nullif(trim(p_item->>'image_path'),''),nullif(trim(p_item->>'icon_svg_path'),'')),nullif(trim(p_item->>'image_alt'),''),v_order,v_status::public.catalog_status) returning id into v_id;
      else select category_id into v_old_parent from public.catalog_subcategories where id=p_id;if v_old_parent<>v_parent and (exists(select 1 from public.products x where x.subcategory_id=p_id) or exists(select 1 from public.product_subcategory_links x where x.subcategory_id=p_id) or exists(select 1 from public.homepage_shop_by_category_items x where x.subcategory_id=p_id) or exists(select 1 from public.navbar_sections x where x.source_subcategory_id=p_id)) then raise exception 'A referenced subcategory cannot be moved to another category.' using errcode='P0001';end if;update public.catalog_subcategories x set category_id=v_parent,name=v_name,slug=v_slug,sub_type=coalesce(p_item->>'sub_type','standard')::public.catalog_sub_type,icon_svg_path=nullif(trim(p_item->>'icon_svg_path'),''),image_path=nullif(trim(p_item->>'image_path'),''),image_alt=nullif(trim(p_item->>'image_alt'),''),display_order=v_order,status=v_status::public.catalog_status,updated_at=now() where x.id=p_id;v_id:=p_id;
      end if;
    when 'option' then
      if exists(select 1 from jsonb_object_keys(p_item) k where k<>all(array['subcategory_id','name','slug','icon_svg_path','image_path','image_alt','display_order','status'])) then raise exception 'Option payload contains unsupported fields.' using errcode='22023';end if;
      v_parent:=nullif(p_item->>'subcategory_id','')::uuid;if not exists(select 1 from public.catalog_subcategories x where x.id=v_parent) then raise exception 'Parent subcategory does not exist.' using errcode='23503';end if;
      if exists(select 1 from public.catalog_options x where x.subcategory_id=v_parent and (lower(x.name)=lower(v_name) or x.slug=v_slug) and (p_id is null or x.id<>p_id)) then raise exception 'An option with this name or slug already exists in the subcategory.' using errcode='23505';end if;
      if p_id is null then insert into public.catalog_options(subcategory_id,name,slug,icon_svg_path,image_path,image_alt,display_order,status) values(v_parent,v_name,v_slug,nullif(trim(p_item->>'icon_svg_path'),''),coalesce(nullif(trim(p_item->>'image_path'),''),nullif(trim(p_item->>'icon_svg_path'),'')),nullif(trim(p_item->>'image_alt'),''),v_order,v_status::public.catalog_status) returning id into v_id;
      else select subcategory_id into v_old_parent from public.catalog_options where id=p_id;if v_old_parent<>v_parent and (exists(select 1 from public.products x where x.option_id=p_id) or exists(select 1 from public.product_option_links x where x.option_id=p_id) or exists(select 1 from public.product_style_selections x where x.option_id=p_id) or exists(select 1 from public.homepage_shop_by_category_items x where x.option_id=p_id)) then raise exception 'A referenced option cannot be moved to another subcategory.' using errcode='P0001';end if;update public.catalog_options x set subcategory_id=v_parent,name=v_name,slug=v_slug,icon_svg_path=nullif(trim(p_item->>'icon_svg_path'),''),image_path=nullif(trim(p_item->>'image_path'),''),image_alt=nullif(trim(p_item->>'image_alt'),''),display_order=v_order,status=v_status::public.catalog_status,updated_at=now() where x.id=p_id;v_id:=p_id;
      end if;
    else raise exception 'Unsupported catalog hierarchy type.' using errcode='22023';
  end case;
  v_result:=public.catalog_hierarchy_row_v1(p_kind,v_id);insert into public.cms_save_receipts(actor_id,request_id,operation,payload_hash,result) values(p_actor_id,p_request_id,'catalog-hierarchy-save-'||p_kind,v_hash,v_result);return v_result;
exception when unique_violation then raise exception 'A hierarchy record with the same name, code, or slug already exists.' using errcode='23505';end $$;

create or replace function public.catalog_hierarchy_delete_v1(p_actor_id uuid,p_request_id uuid,p_expected_revision text,p_kind text,p_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_before jsonb;v_receipt public.cms_save_receipts%rowtype;v_hash text:=md5(jsonb_build_object('kind',p_kind,'id',p_id,'revision',p_expected_revision)::text);v_count int:=0;v_locked boolean;v_result jsonb;
begin
  if not exists(select 1 from public.profiles p where p.id=p_actor_id and p.role='admin') then raise exception 'Administrator access is required.' using errcode='42501';end if;if p_request_id is null or p_id is null or p_expected_revision is null then raise exception 'Invalid hierarchy delete request.' using errcode='22023';end if;perform pg_advisory_xact_lock(hashtextextended('catalog-request:'||p_actor_id||':'||p_request_id,0));select * into v_receipt from public.cms_save_receipts r where r.actor_id=p_actor_id and r.request_id=p_request_id;if found then if v_receipt.operation<>'catalog-hierarchy-delete-'||p_kind or v_receipt.payload_hash<>v_hash then raise exception 'This request ID was already used.' using errcode='22023';end if;return v_receipt.result;end if;
  perform pg_advisory_xact_lock(hashtextextended('catalog-hierarchy:'||p_kind||':'||p_id,0));v_before:=public.catalog_hierarchy_row_v1(p_kind,p_id);if v_before->'item'='null'::jsonb then raise exception 'Hierarchy record not found.' using errcode='P0002';end if;if v_before->>'revision'<>p_expected_revision then raise exception 'This hierarchy record changed since you opened it. Reload before deleting.' using errcode='40001';end if;
  case p_kind
    when 'category' then select is_system_locked into v_locked from public.catalog_categories where id=p_id;if v_locked then raise exception 'Protected system categories cannot be deleted.' using errcode='42501';end if;select (select count(*) from public.catalog_subcategories where category_id=p_id)+(select count(*) from public.products where main_category_id=p_id)+(select count(*) from public.blog_posts where catalog_category_id=p_id)+(select count(*) from public.support_faq_items where catalog_category_id=p_id)+(select count(*) from public.category_grid_posters where category_id=p_id)+(select count(*) from public.homepage_shop_by_category_items where category_id=p_id)+(select count(*) from public.navbar_sections where linked_category_id=p_id)+(select count(*) from public.navbar_items where linked_category_id=p_id) into v_count;if v_count>0 then raise exception 'This category is used in % place(s). Hide it instead of deleting it.',v_count using errcode='P0001';end if;delete from public.catalog_categories where id=p_id;
    when 'subcategory' then select (select count(*) from public.catalog_options where subcategory_id=p_id)+(select count(*) from public.products where subcategory_id=p_id)+(select count(*) from public.product_subcategory_links where subcategory_id=p_id)+(select count(*) from public.homepage_shop_by_category_items where subcategory_id=p_id)+(select count(*) from public.navbar_sections where source_subcategory_id=p_id) into v_count;if v_count>0 then raise exception 'This subcategory is used in % place(s). Hide it instead of deleting it.',v_count using errcode='P0001';end if;delete from public.catalog_subcategories where id=p_id;
    when 'option' then select (select count(*) from public.products where option_id=p_id)+(select count(*) from public.product_option_links where option_id=p_id)+(select count(*) from public.product_style_selections where option_id=p_id)+(select count(*) from public.homepage_shop_by_category_items where option_id=p_id) into v_count;if v_count>0 then raise exception 'This option is used in % place(s). Hide it instead of deleting it.',v_count using errcode='P0001';end if;delete from public.catalog_options where id=p_id;
    else raise exception 'Unsupported catalog hierarchy type.' using errcode='22023';end case;
  v_result:=jsonb_build_object('ok',true,'id',p_id);insert into public.cms_save_receipts(actor_id,request_id,operation,payload_hash,result) values(p_actor_id,p_request_id,'catalog-hierarchy-delete-'||p_kind,v_hash,v_result);return v_result;
end $$;

revoke all on function public.catalog_hierarchy_list_v1(text) from public,anon,authenticated;revoke all on function public.catalog_hierarchy_row_v1(text,uuid) from public,anon,authenticated;revoke all on function public.catalog_hierarchy_save_v1(uuid,uuid,text,text,uuid,jsonb) from public,anon,authenticated;revoke all on function public.catalog_hierarchy_delete_v1(uuid,uuid,text,text,uuid) from public,anon,authenticated;
grant execute on function public.catalog_hierarchy_list_v1(text) to service_role;grant execute on function public.catalog_hierarchy_row_v1(text,uuid) to service_role;grant execute on function public.catalog_hierarchy_save_v1(uuid,uuid,text,text,uuid,jsonb) to service_role;grant execute on function public.catalog_hierarchy_delete_v1(uuid,uuid,text,text,uuid) to service_role;notify pgrst,'reload schema';commit;
